export type Role = {
  label: string;
  description: string;
};

export type JobCategory = {
  category: string;
  roles: Role[];
};

export const JOB_CATEGORIES: JobCategory[] = [
  {
    category: "Software Engineering",
    roles: [
      {
        label: "Frontend Developer",
        description:
          "We are looking for a skilled Frontend Developer to join our product engineering team and help us build fast, accessible, and visually compelling user interfaces. You will work closely with designers and backend engineers to ship features that reach millions of users.\n\nResponsibilities:\n• Build and maintain responsive web applications using React and TypeScript\n• Implement pixel-perfect UI components from Figma designs with attention to accessibility and cross-browser compatibility\n• Optimize application performance through code splitting, lazy loading, and bundle size analysis\n• Write unit and integration tests using Jest and React Testing Library\n• Collaborate with backend engineers to design and consume REST APIs and GraphQL endpoints\n• Participate in code reviews, maintain coding standards, and mentor junior developers\n• Drive improvements to our frontend build pipeline using Webpack and Vite\n\nRequirements:\n• 3+ years of professional experience building production web applications\n• Expert-level proficiency in React, TypeScript, and modern JavaScript (ES2022+)\n• Strong understanding of HTML5, CSS3, and responsive design principles\n• Experience with state management libraries such as Redux Toolkit or Zustand\n• Familiarity with testing frameworks including Jest and Cypress\n• Proficiency with Git, GitHub, and pull request workflows\n• Understanding of web performance metrics including Core Web Vitals, LCP, and CLS\n\nNice to Have:\n• Experience with Next.js, server-side rendering, and edge deployments on Vercel or Cloudflare\n• Familiarity with WebSockets, WebRTC, or real-time data patterns\n• Prior contributions to open-source projects or a public GitHub portfolio",
      },
      {
        label: "Backend Developer",
        description:
          "Our team is seeking an experienced Backend Developer to design and build the APIs, services, and data pipelines that power our platform. You will own critical backend systems and work across the stack to ensure reliability, performance, and scalability.\n\nResponsibilities:\n• Design, build, and maintain RESTful APIs and microservices using Node.js and TypeScript or Python\n• Architect and optimize relational database schemas in PostgreSQL and manage query performance\n• Implement caching strategies using Redis to reduce latency and database load\n• Build asynchronous data processing pipelines using message queues such as RabbitMQ or Apache Kafka\n• Own deployment configurations and work with DevOps to ship services via Docker and Kubernetes\n• Write comprehensive test suites using Jest or Pytest to ensure service reliability\n• Participate in on-call rotations and respond to production incidents with urgency\n\nRequirements:\n• 4+ years of backend engineering experience in a production environment\n• Strong proficiency in Node.js with TypeScript or Python (Django, FastAPI, or Flask)\n• Deep experience with PostgreSQL including query optimization, indexing, and schema design\n• Hands-on experience with Redis for caching, session management, and pub/sub\n• Familiarity with Docker, Kubernetes, and container orchestration in AWS or GCP\n• Solid understanding of REST API design principles, authentication (OAuth 2.0, JWT), and API versioning\n• Experience with CI/CD pipelines using GitHub Actions, Jenkins, or CircleCI\n\nNice to Have:\n• Experience with GraphQL and schema-first API design using Apollo Server\n• Familiarity with event-driven architecture and Apache Kafka or AWS SQS\n• Knowledge of Terraform for infrastructure-as-code provisioning",
      },
      {
        label: "Full Stack Developer",
        description:
          "We are looking for a Full Stack Developer who thrives across the entire web application stack — from designing intuitive React interfaces to architecting robust Node.js backends and managing cloud infrastructure. This is a high-ownership role where you will contribute to every layer of the product.\n\nResponsibilities:\n• Build end-to-end product features spanning React frontends, Node.js APIs, and PostgreSQL databases\n• Design and implement GraphQL and REST APIs consumed by web and mobile clients\n• Develop reusable React component libraries with TypeScript and document them in Storybook\n• Manage cloud infrastructure on AWS using services including EC2, RDS, S3, Lambda, and CloudFront\n• Implement authentication and authorization flows using OAuth 2.0 and JSON Web Tokens\n• Write automated tests using Jest, React Testing Library, and Playwright for end-to-end coverage\n• Review code, participate in architecture discussions, and contribute to technical roadmap planning\n\nRequirements:\n• 4+ years of full stack development experience shipping production applications\n• Proficiency in React, TypeScript, and Next.js for server-rendered and static web applications\n• Strong backend skills in Node.js with Express or Fastify and experience with RESTful API design\n• Working knowledge of PostgreSQL and MongoDB including schema design and query optimization\n• Experience deploying and managing applications on AWS or GCP\n• Comfort with Docker, Docker Compose, and basic Kubernetes concepts\n• Solid Git workflow experience including branching strategies, code review, and CI/CD integration\n\nNice to Have:\n• Experience with tRPC or GraphQL for type-safe API development\n• Familiarity with serverless architectures using AWS Lambda or Vercel Edge Functions\n• Previous experience in an early-stage startup environment with broad ownership expectations",
      },
      {
        label: "Mobile Developer (iOS/Android)",
        description:
          "Our team is seeking a talented Mobile Developer to lead the development of our consumer-facing iOS and Android applications. You will be responsible for delivering smooth, native-quality experiences to a rapidly growing user base across both platforms.\n\nResponsibilities:\n• Build and ship cross-platform mobile features using React Native and TypeScript\n• Implement native modules in Swift (iOS) and Kotlin (Android) when React Native abstractions are insufficient\n• Optimize application startup time, rendering performance, and memory usage on both platforms\n• Integrate REST APIs and GraphQL endpoints with robust offline support using local SQLite caching\n• Implement push notifications using APNs, Firebase Cloud Messaging (FCM), and OneSignal\n• Submit and manage app releases through Apple App Store Connect and Google Play Console\n• Write unit tests with Jest and end-to-end tests using Detox for mobile UI flows\n\nRequirements:\n• 3+ years of mobile development experience with React Native in a production app\n• Proficiency in TypeScript and familiarity with both Swift and Kotlin for native module development\n• Experience with React Navigation, Redux Toolkit or Zustand for state management\n• Understanding of mobile performance profiling using Xcode Instruments and Android Studio Profiler\n• Knowledge of App Store and Google Play submission processes, code signing, and provisioning profiles\n• Experience integrating third-party SDKs such as Stripe, Segment, Sentry, and Firebase\n• Solid Git workflow and experience with mobile CI/CD using Fastlane, GitHub Actions, or Bitrise\n\nNice to Have:\n• Experience building with Expo and Expo EAS Build for managed and bare workflow projects\n• Familiarity with Bluetooth Low Energy (BLE) or device hardware API integrations\n• Prior app launches with 100K+ downloads and strong App Store ratings",
      },
      {
        label: "DevOps Engineer",
        description:
          "We are looking for a DevOps Engineer to build and maintain the infrastructure, tooling, and deployment pipelines that enable our engineering teams to ship software confidently and quickly. You will be a force multiplier for the entire organization.\n\nResponsibilities:\n• Design, implement, and maintain CI/CD pipelines using GitHub Actions, Jenkins, and ArgoCD\n• Manage and scale Kubernetes clusters on AWS EKS and GCP GKE in production environments\n• Write and maintain Terraform and Helm configurations for repeatable infrastructure provisioning\n• Monitor system health using Datadog, Prometheus, and Grafana and respond to alerting incidents\n• Implement security best practices including IAM role policies, secrets management with HashiCorp Vault, and network segmentation\n• Automate operational tasks using Python and Bash scripting\n• Partner with development teams to define SLOs, SLAs, and error budgets\n\nRequirements:\n• 4+ years of DevOps or infrastructure engineering experience in a cloud-native environment\n• Expert-level knowledge of AWS services including EKS, EC2, RDS, S3, VPC, IAM, and CloudWatch\n• Strong proficiency with Terraform for infrastructure-as-code across multiple environments\n• Hands-on Kubernetes experience including workload management, RBAC, Ingress, and Helm chart authoring\n• Experience building and maintaining CI/CD pipelines with GitHub Actions or Jenkins\n• Proficiency in Linux systems administration and shell scripting (Bash)\n• Familiarity with Docker and container image optimization strategies\n\nNice to Have:\n• AWS Certified DevOps Engineer or Certified Kubernetes Administrator (CKA) certification\n• Experience with service mesh technologies such as Istio or Linkerd\n• Knowledge of GitOps workflows using ArgoCD or Flux",
      },
      {
        label: "Cloud Engineer",
        description:
          "Our team is seeking a Cloud Engineer to architect, deploy, and optimize our cloud infrastructure across AWS and GCP. You will work alongside platform and application teams to design resilient, cost-efficient, and secure cloud environments that support our global operations.\n\nResponsibilities:\n• Architect multi-region cloud environments on AWS and GCP with a focus on high availability and disaster recovery\n• Develop and maintain Terraform modules for provisioning VPCs, subnets, load balancers, databases, and compute resources\n• Implement cloud cost optimization strategies using AWS Cost Explorer, Reserved Instances, and right-sizing recommendations\n• Design and enforce IAM policies, SCPs, and cloud security posture management (CSPM) controls\n• Build and maintain data pipelines using AWS Glue, Lambda, S3, and Kinesis\n• Manage containerized workloads on EKS and ECS with auto-scaling configurations\n• Create runbooks, architecture diagrams, and infrastructure documentation for operational handoff\n\nRequirements:\n• 4+ years of cloud engineering experience with deep AWS expertise\n• Strong hands-on experience with Terraform and infrastructure-as-code practices\n• Proficiency with AWS services including VPC, EC2, EKS, RDS, S3, Lambda, CloudFormation, and Route 53\n• Experience with GCP services including GKE, Cloud Run, BigQuery, and Cloud Storage\n• Working knowledge of networking concepts: BGP, VPNs, Direct Connect, Transit Gateway, and DNS\n• Familiarity with Python or Go for automation scripting and Lambda function development\n• AWS Solutions Architect Associate or Professional certification preferred\n\nNice to Have:\n• Google Cloud Professional Cloud Architect certification\n• Experience with multi-cloud networking and cross-cloud identity federation\n• Familiarity with FinOps practices and cloud cost governance frameworks",
      },
      {
        label: "Site Reliability Engineer",
        description:
          "We are looking for a Site Reliability Engineer to ensure our platform remains highly available, performant, and operationally excellent at scale. You will embed with product engineering teams, apply SRE principles, and drive systemic reliability improvements across our infrastructure.\n\nResponsibilities:\n• Define and track SLOs, SLIs, and error budgets for critical platform services\n• Lead blameless post-mortems and drive long-term remediation of reliability gaps\n• Build and maintain observability infrastructure using Datadog, Prometheus, Grafana, and PagerDuty\n• Develop internal tooling and automation in Go or Python to reduce operational toil\n• Participate in on-call rotations and own incident response, escalation, and communication\n• Conduct capacity planning analyses and implement auto-scaling strategies on Kubernetes\n• Review system designs for reliability, failure modes, and operational burden before launch\n\nRequirements:\n• 4+ years of SRE, platform engineering, or senior DevOps experience\n• Deep understanding of distributed systems, failure domains, and cascading failure patterns\n• Strong proficiency with Kubernetes in production including HPA, VPA, cluster autoscaler, and pod disruption budgets\n• Experience building monitoring dashboards and alerting pipelines with Prometheus and Grafana\n• Proficiency in Python or Go for automation, tooling, and infrastructure scripting\n• Hands-on experience with AWS or GCP and managed services at scale\n• Experience with chaos engineering tools such as Chaos Monkey or Gremlin\n\nNice to Have:\n• Experience with distributed tracing using Jaeger, Zipkin, or OpenTelemetry\n• Familiarity with service mesh configuration and observability via Istio\n• Prior experience in a high-traffic consumer product environment (10M+ daily active users)",
      },
      {
        label: "QA / Test Engineer",
        description:
          "Our team is seeking a QA / Test Engineer to champion quality across our entire software delivery lifecycle. You will design and implement test strategies, build automated test frameworks, and partner with engineers and product managers to ensure every release meets our high reliability bar.\n\nResponsibilities:\n• Design, implement, and maintain automated test suites for unit, integration, and end-to-end testing\n• Build Playwright and Cypress test frameworks for web application UI automation\n• Develop API test suites using Postman, Newman, and REST Assured for backend service validation\n• Perform exploratory, regression, and performance testing on new and existing features\n• Integrate automated tests into CI/CD pipelines using GitHub Actions and Jenkins\n• Analyze test results, file detailed bug reports in Jira, and work with engineers to drive resolution\n• Define and enforce quality gates, test coverage thresholds, and release criteria\n\nRequirements:\n• 3+ years of QA engineering experience with a strong emphasis on test automation\n• Proficiency in Playwright or Cypress for browser-based end-to-end test automation\n• Experience writing automated API tests using Postman, Newman, or a code-based framework\n• Solid programming skills in TypeScript or Python for test framework development\n• Familiarity with performance testing tools such as k6, JMeter, or Locust\n• Experience integrating test automation into CI/CD pipelines with GitHub Actions or Jenkins\n• Strong understanding of Agile and Scrum development workflows and quality gates\n\nNice to Have:\n• ISTQB Foundation or Advanced certification\n• Experience with mobile test automation using Detox or Appium\n• Familiarity with accessibility testing tools such as Axe, Lighthouse, and WAVE",
      },
      {
        label: "Embedded Systems Engineer",
        description:
          "We are looking for an Embedded Systems Engineer to design and develop firmware and low-level software for our connected hardware products. You will work at the intersection of hardware and software, collaborating with electrical engineers and cloud backend teams to ship reliable, efficient embedded solutions.\n\nResponsibilities:\n• Develop and maintain firmware in C and C++ for ARM Cortex-M microcontrollers (STM32, nRF52 series)\n• Implement RTOS-based task scheduling using FreeRTOS with a focus on deterministic timing and low power consumption\n• Design and integrate communication protocol stacks including UART, SPI, I2C, BLE, and MQTT\n• Write board support packages (BSPs) and hardware abstraction layers (HALs) for new hardware revisions\n• Debug hardware and firmware issues using oscilloscopes, logic analyzers, and JTAG/SWD debuggers\n• Collaborate with cloud engineers to implement OTA firmware update mechanisms over MQTT and HTTPS\n• Write unit tests using CppUTest or Unity and maintain CI pipelines for firmware build validation\n\nRequirements:\n• 4+ years of embedded firmware development experience in a production hardware product\n• Expert-level proficiency in C and working knowledge of C++ for embedded targets\n• Hands-on experience with ARM Cortex-M architecture and STM32 or Nordic Semiconductor nRF52 families\n• Strong understanding of FreeRTOS, task management, semaphores, and interrupt service routines\n• Experience with hardware communication protocols: UART, SPI, I2C, CAN, and BLE\n• Proficiency with debugging tools including JTAG, SWD, GDB, and logic analyzers\n• Familiarity with Makefile, CMake, and embedded build toolchains (GCC ARM)\n\nNice to Have:\n• Experience with Zephyr RTOS or Mbed OS as an alternative to FreeRTOS\n• Knowledge of TLS/DTLS for secure embedded communication\n• Familiarity with AWS IoT Core or Azure IoT Hub for device-to-cloud connectivity",
      },
    ],
  },
  {
    category: "Data & AI",
    roles: [
      {
        label: "Data Analyst",
        description:
          "Our team is seeking a Data Analyst to transform raw data into actionable business insights that drive strategic decision-making across product, marketing, and operations. You will be a key partner to cross-functional stakeholders and a steward of data quality and accuracy.\n\nResponsibilities:\n• Design and maintain dashboards and reports in Tableau, Looker, or Power BI for business stakeholders\n• Write complex SQL queries against data warehouses (Snowflake, BigQuery) to extract and analyze large datasets\n• Conduct ad hoc analyses to answer business questions around user behavior, revenue, and product performance\n• Build and maintain data models using dbt (data build tool) for consistent, reusable metric definitions\n• Partner with data engineers to define data requirements and validate pipeline outputs\n• Present findings clearly to non-technical audiences and translate insights into recommendations\n• Establish data quality monitoring and alerting to detect anomalies and upstream issues\n\nRequirements:\n• 3+ years of experience in a data analyst or business intelligence role\n• Expert-level SQL skills across multiple dialects (PostgreSQL, BigQuery SQL, Snowflake SQL)\n• Proficiency with Tableau, Looker, or Power BI for dashboard creation and data storytelling\n• Experience working with dbt for data transformation and modeling in a modern data stack\n• Solid understanding of statistical concepts including A/B testing, cohort analysis, and funnel analysis\n• Proficiency in Python or R for data cleaning, EDA, and lightweight statistical modeling\n• Familiarity with cloud data platforms including Snowflake, BigQuery, or AWS Redshift\n\nNice to Have:\n• Experience with Google Analytics 4, Amplitude, or Mixpanel for product analytics\n• Knowledge of data governance principles and experience with tools like Alation or Atlan\n• Familiarity with Apache Airflow for understanding data pipeline dependencies",
      },
      {
        label: "Data Engineer",
        description:
          "We are looking for a Data Engineer to design, build, and maintain the scalable data infrastructure that powers our analytics, machine learning, and business intelligence capabilities. You will ensure data is reliable, accessible, and well-documented across the organization.\n\nResponsibilities:\n• Design and build ELT/ETL data pipelines using Apache Airflow, dbt, and Python\n• Develop and maintain data models in Snowflake and BigQuery optimized for analytical workloads\n• Ingest data from diverse sources including REST APIs, Kafka streams, PostgreSQL, and third-party SaaS tools using Fivetran and Airbyte\n• Implement data quality checks, validation frameworks, and alerting using Great Expectations or dbt tests\n• Maintain and optimize Apache Spark jobs for large-scale batch data processing on AWS EMR or Databricks\n• Collaborate with data scientists and analysts to understand data requirements and design efficient schemas\n• Build and enforce data governance standards including lineage tracking, PII handling, and access controls\n\nRequirements:\n• 3+ years of data engineering experience in a production data environment\n• Strong Python programming skills with experience in Pandas, PySpark, and SQL\n• Expert-level SQL proficiency with Snowflake, BigQuery, or AWS Redshift\n• Hands-on experience with Apache Airflow for pipeline orchestration and DAG authoring\n• Experience with dbt for data transformation, testing, and documentation\n• Familiarity with streaming data platforms including Apache Kafka or AWS Kinesis\n• Knowledge of data warehouse design patterns including star schema, slowly changing dimensions, and data vault\n\nNice to Have:\n• Experience with Databricks and Delta Lake for lakehouse architecture\n• Familiarity with infrastructure-as-code tools such as Terraform for data infrastructure management\n• Knowledge of real-time analytics using Apache Flink or ksqlDB",
      },
      {
        label: "Data Scientist",
        description:
          "Our team is seeking a Data Scientist to develop statistical models, machine learning algorithms, and analytical frameworks that solve real business problems and improve our product experience. You will work closely with engineering, product, and business leaders to drive data-informed decisions.\n\nResponsibilities:\n• Design and implement machine learning models for recommendation, classification, forecasting, and anomaly detection using Python, scikit-learn, and XGBoost\n• Conduct rigorous A/B experiments and analyze results using statistical hypothesis testing (t-tests, chi-squared, Bayesian methods)\n• Build and maintain data analysis pipelines using Pandas, NumPy, and SQL on Snowflake or BigQuery\n• Develop and deploy models to production using MLflow for experiment tracking and model registry\n• Create compelling data visualizations and communicate findings clearly to technical and non-technical stakeholders\n• Collaborate with data engineers to define feature engineering requirements and pipeline specifications\n• Identify new opportunities to apply machine learning and statistical modeling to product and business challenges\n\nRequirements:\n• 3+ years of data science experience in a production ML environment\n• Strong Python programming skills including Pandas, NumPy, scikit-learn, and Matplotlib\n• Expert-level SQL for complex data extraction and transformation from Snowflake or BigQuery\n• Solid grounding in statistics: regression, classification, clustering, A/B testing, and Bayesian inference\n• Experience with gradient boosting frameworks such as XGBoost, LightGBM, or CatBoost\n• Familiarity with MLflow, Weights & Biases, or similar experiment tracking and model management tools\n• Proficiency with Jupyter notebooks and collaborative data science workflows in Git\n\nNice to Have:\n• Experience with deep learning frameworks such as TensorFlow or PyTorch\n• Familiarity with feature stores such as Feast or Tecton\n• Background in causal inference, uplift modeling, or econometrics",
      },
      {
        label: "Machine Learning Engineer",
        description:
          "We are looking for a Machine Learning Engineer to bridge the gap between research and production — taking models from experimentation to reliable, scalable ML systems that power our core product features. You will own the full ML lifecycle from feature engineering through deployment and monitoring.\n\nResponsibilities:\n• Develop, train, and optimize machine learning models using PyTorch and TensorFlow for production deployment\n• Build scalable feature engineering pipelines using Apache Spark, Feast, or AWS SageMaker Feature Store\n• Deploy models as low-latency REST APIs using FastAPI, TorchServe, or AWS SageMaker endpoints\n• Implement model monitoring, data drift detection, and automated retraining pipelines using MLflow and Evidently\n• Optimize model inference performance through quantization, ONNX conversion, and GPU batching\n• Collaborate with data scientists to productionize research models and improve training pipelines\n• Design and implement A/B testing infrastructure to evaluate model performance in production\n\nRequirements:\n• 4+ years of machine learning engineering experience deploying models to production\n• Strong proficiency in Python and deep familiarity with PyTorch and TensorFlow\n• Experience with MLflow, Kubeflow, or AWS SageMaker for end-to-end ML pipeline management\n• Solid software engineering skills: clean code, unit testing with Pytest, Git, and code review\n• Experience deploying ML models as REST APIs using FastAPI or Flask on Docker and Kubernetes\n• Familiarity with distributed training frameworks and GPU cluster management\n• Working knowledge of SQL and big data tools including Apache Spark or Databricks\n\nNice to Have:\n• Experience with LLM fine-tuning using Hugging Face Transformers and PEFT/LoRA\n• Familiarity with vector databases such as Pinecone, Weaviate, or Qdrant\n• Knowledge of ONNX Runtime and TensorRT for model optimization and inference acceleration",
      },
      {
        label: "AI/ML Research Scientist",
        description:
          "Our team is seeking an AI/ML Research Scientist to push the boundaries of what our AI systems can do. You will conduct original research, develop novel algorithms, and translate cutting-edge academic findings into practical improvements to our products and models.\n\nResponsibilities:\n• Conduct original research in areas including large language models, reinforcement learning, generative AI, and representation learning\n• Design and run controlled experiments to evaluate novel model architectures against established baselines\n• Publish research findings at top-tier venues such as NeurIPS, ICML, ICLR, ACL, or EMNLP\n• Implement and benchmark state-of-the-art techniques from recent academic literature using PyTorch\n• Collaborate with ML engineers to transfer research prototypes into production-ready systems\n• Train large-scale models on GPU clusters using distributed training frameworks including DeepSpeed and FSDP\n• Mentor junior researchers and contribute to a culture of scientific rigor and intellectual curiosity\n\nRequirements:\n• PhD in Machine Learning, Computer Science, Statistics, or a closely related field, or equivalent research experience\n• Expert-level proficiency in Python and PyTorch for research prototyping and experimentation\n• Deep understanding of transformer architectures, attention mechanisms, and pre-training methodologies\n• Experience with distributed training using DeepSpeed, PyTorch FSDP, or Horovod on multi-GPU and multi-node setups\n• Strong publication record at peer-reviewed ML or AI venues\n• Solid mathematical foundation in linear algebra, calculus, probability theory, and optimization\n• Familiarity with Hugging Face Transformers, Datasets, and the broader OSS ML ecosystem\n\nNice to Have:\n• Experience with RLHF (Reinforcement Learning from Human Feedback) and preference optimization methods\n• Familiarity with multimodal model architectures (vision-language models, audio-text models)\n• Open-source contributions to major ML libraries or released model weights",
      },
      {
        label: "NLP Engineer",
        description:
          "We are looking for an NLP Engineer to design and build natural language understanding and generation systems that power intelligent features across our platform. You will work with large language models, text classification, information extraction, and conversational AI.\n\nResponsibilities:\n• Design and implement NLP pipelines for tasks including text classification, named entity recognition (NER), summarization, and semantic similarity using Hugging Face Transformers\n• Fine-tune pre-trained language models (BERT, RoBERTa, GPT variants, LLaMA) using PEFT, LoRA, and full fine-tuning techniques on domain-specific datasets\n• Build and optimize Retrieval-Augmented Generation (RAG) pipelines using LangChain, LlamaIndex, and vector databases including Pinecone and Weaviate\n• Develop text preprocessing, tokenization, and annotation pipelines for training data curation\n• Evaluate model performance using standard NLP metrics (F1, BLEU, ROUGE, BERTScore) and human evaluation frameworks\n• Deploy NLP models as production APIs on AWS SageMaker or Docker/Kubernetes environments\n• Stay current with advances in LLMs, prompting techniques, and NLP research\n\nRequirements:\n• 3+ years of NLP engineering experience in a production environment\n• Strong Python programming skills and deep expertise with Hugging Face Transformers and Datasets\n• Hands-on experience fine-tuning transformer models for classification, extraction, or generation tasks\n• Familiarity with LangChain, LlamaIndex, or similar LLM orchestration frameworks\n• Experience with vector databases including Pinecone, Weaviate, Chroma, or Qdrant\n• Solid understanding of NLP fundamentals: tokenization, embeddings, attention mechanisms, and language model pretraining\n• Experience deploying ML models using FastAPI, Docker, and AWS or GCP\n\nNice to Have:\n• Experience with OpenAI API, Anthropic Claude, or Cohere APIs for LLM application development\n• Familiarity with spaCy for production NLP pipeline development\n• Background in computational linguistics or prior research publications in NLP",
      },
      {
        label: "Computer Vision Engineer",
        description:
          "Our team is seeking a Computer Vision Engineer to build perception systems that extract meaning from images and video at scale. You will develop and deploy state-of-the-art models for object detection, segmentation, classification, and visual understanding tasks.\n\nResponsibilities:\n• Design and train deep learning models for object detection, image classification, semantic segmentation, and instance segmentation using PyTorch and TensorFlow\n• Implement and fine-tune state-of-the-art architectures including YOLO, Detectron2, Segment Anything Model (SAM), and Vision Transformers (ViT)\n• Build data annotation pipelines and work with tools such as Labelbox, Scale AI, and Roboflow to curate high-quality training datasets\n• Optimize models for edge and mobile deployment using TensorRT, ONNX Runtime, and CoreML\n• Build real-time video inference pipelines using OpenCV, GStreamer, and CUDA-accelerated processing\n• Evaluate model performance using mAP, IoU, precision/recall curves, and confusion matrix analysis\n• Deploy vision models to production using Docker, Triton Inference Server, and AWS SageMaker\n\nRequirements:\n• 4+ years of computer vision engineering experience in a production ML environment\n• Expert-level proficiency in PyTorch and familiarity with TensorFlow for model development\n• Deep knowledge of CNN architectures (ResNet, EfficientNet, MobileNet) and Vision Transformers\n• Hands-on experience with object detection frameworks including YOLO (v8/v9), Detectron2, or MMDetection\n• Strong OpenCV and NumPy skills for image processing and data augmentation pipelines\n• Experience with TensorRT, ONNX, or CoreML for model optimization and edge deployment\n• Proficiency in Python and familiarity with CUDA programming for GPU-accelerated inference\n\nNice to Have:\n• Experience with 3D vision, LiDAR point cloud processing, or depth estimation\n• Familiarity with generative models including GANs, diffusion models, or NeRF\n• Background in autonomous systems, robotics, or medical imaging applications",
      },
      {
        label: "MLOps Engineer",
        description:
          "We are looking for an MLOps Engineer to build the infrastructure, tooling, and best practices that enable our data science and ML engineering teams to develop, train, deploy, and monitor machine learning models efficiently and reliably at scale.\n\nResponsibilities:\n• Design and implement end-to-end ML pipelines on Kubeflow, MLflow, or AWS SageMaker Pipelines\n• Build model serving infrastructure supporting low-latency REST and gRPC inference using Triton Inference Server and KServe\n• Implement model monitoring systems to detect data drift, prediction drift, and model degradation using Evidently and Grafana\n• Automate model retraining triggers and CI/CD pipelines for ML model lifecycle management using GitHub Actions and Jenkins\n• Manage ML infrastructure on Kubernetes with GPU node pools, resource quotas, and job scheduling\n• Maintain feature stores and ensure consistent feature computation between training and serving environments\n• Establish MLOps best practices, documentation, and internal developer tooling to accelerate the ML team\n\nRequirements:\n• 3+ years of MLOps, ML platform engineering, or closely related infrastructure engineering experience\n• Strong proficiency in Python and familiarity with PyTorch and TensorFlow model packaging\n• Hands-on experience with MLflow for experiment tracking, model registry, and deployment\n• Experience with Kubeflow Pipelines, AWS SageMaker Pipelines, or Vertex AI Pipelines\n• Solid Kubernetes skills including GPU workload management, Helm charts, and autoscaling\n• Familiarity with Docker for containerizing training jobs and model serving runtimes\n• Experience with CI/CD tooling (GitHub Actions, Jenkins, ArgoCD) and GitOps workflows\n\nNice to Have:\n• Experience with Feast, Tecton, or Hopsworks as a feature store platform\n• Familiarity with data versioning tools such as DVC (Data Version Control)\n• Knowledge of Seldon Core, BentoML, or Ray Serve for model serving at scale",
      },
    ],
  },
  {
    category: "Design",
    roles: [
      {
        label: "UI/UX Designer",
        description:
          "Our team is seeking a UI/UX Designer to create exceptional user experiences for our web and mobile products. You will own the design process from discovery through delivery, collaborating closely with product managers and engineers to ship interfaces that are both beautiful and deeply functional.\n\nResponsibilities:\n• Lead end-to-end UX design for new product features — from user research and journey mapping through wireframes, prototypes, and high-fidelity Figma designs\n• Conduct usability testing sessions, synthesize findings, and iterate designs based on user feedback\n• Design and maintain a scalable component-based design system in Figma with comprehensive documentation\n• Collaborate with frontend engineers to ensure pixel-accurate implementation and provide design QA\n• Create user flow diagrams, information architecture maps, and interaction specifications\n• Apply accessibility standards (WCAG 2.1 AA) to all design work and advocate for inclusive design practices\n• Partner with product managers to align design decisions with business goals and user needs\n\nRequirements:\n• 3+ years of UI/UX design experience for web and mobile digital products\n• Expert proficiency in Figma including auto-layout, variants, interactive components, and prototyping\n• Strong portfolio demonstrating end-to-end UX process, visual design skills, and shipped product work\n• Experience conducting user interviews, usability tests, and synthesizing qualitative research\n• Solid understanding of responsive design, design systems, and component-driven design workflows\n• Familiarity with accessibility standards (WCAG 2.1) and inclusive design practices\n• Basic understanding of HTML, CSS, and frontend constraints to facilitate engineering collaboration\n\nNice to Have:\n• Experience with motion design and micro-interaction prototyping using Figma Smart Animate or Principle\n• Familiarity with user research tools such as Maze, UserTesting, or Hotjar\n• Experience designing for data-dense dashboards or complex enterprise SaaS applications",
      },
      {
        label: "Product Designer",
        description:
          "We are looking for a Product Designer to shape how our users interact with our product, from the moment they sign up to their deepest power-user workflows. You will drive design strategy, advocate for the user, and collaborate with cross-functional teams to build experiences that users love.\n\nResponsibilities:\n• Own the design process for a core product surface area — conducting research, defining problems, generating concepts, and shipping polished solutions\n• Create wireframes, user flows, and high-fidelity interactive prototypes in Figma for complex product features\n• Collaborate with product managers to define requirements and translate them into clear UX specifications\n• Contribute to and extend a multi-platform design system ensuring visual and interaction consistency\n• Run structured and unstructured user research including interviews, surveys, and A/B test analysis\n• Work directly with frontend engineers during implementation to resolve design gaps and maintain fidelity\n• Advocate for user-centered design principles in product planning, roadmap discussions, and sprint reviews\n\nRequirements:\n• 4+ years of product design experience at a software company with a strong shipped product portfolio\n• Expert-level Figma skills including design systems, component libraries, and high-fidelity prototyping\n• Demonstrated ability to lead the full design process from ambiguous problem to polished shipped feature\n• Strong visual design skills with a sharp eye for typography, spacing, color, and interaction details\n• Experience with quantitative product analytics tools such as Amplitude, Mixpanel, or Google Analytics 4\n• Familiarity with Agile and Scrum product development workflows and sprint-based design delivery\n• Strong written and verbal communication skills for design critique and cross-functional collaboration\n\nNice to Have:\n• Experience with design tokens and code-connected design systems using Figma Tokens or Style Dictionary\n• Background in designing mobile-first or native iOS/Android experiences\n• Prior experience at a B2C product company with millions of monthly active users",
      },
      {
        label: "Graphic Designer",
        description:
          "Our team is seeking a Graphic Designer to create compelling visual content across digital and print channels that communicates our brand story, drives engagement, and supports marketing and product initiatives. You will be a creative force who can move quickly and think strategically.\n\nResponsibilities:\n• Design high-quality visual assets for digital marketing campaigns including social media, email, display advertising, and landing pages\n• Create brand collateral including presentations, one-pagers, event materials, and print assets with precision in Adobe InDesign and Illustrator\n• Develop motion graphics and short-form animated content using Adobe After Effects for social and paid media\n• Collaborate with the marketing team to concept and execute visual campaigns aligned with brand guidelines\n• Maintain and evolve brand identity systems including typography, color palettes, iconography, and illustration styles\n• Manage multiple design projects simultaneously, prioritizing effectively within tight deadlines\n• Prepare and deliver production-ready files for print vendors and digital ad platforms\n\nRequirements:\n• 3+ years of graphic design experience in a marketing, agency, or in-house brand team\n• Expert proficiency in Adobe Creative Suite including Photoshop, Illustrator, InDesign, and After Effects\n• Strong working knowledge of Figma for collaborative design and web/social asset creation\n• Demonstrated portfolio showing range across digital campaigns, brand identity, and motion graphics\n• Solid understanding of typography systems, grid layouts, color theory, and visual hierarchy\n• Experience preparing files for digital platforms (Google Ads, Meta Ads, LinkedIn) and print production\n• Familiarity with brand management and asset organization using tools like Brandfolder or Bynder\n\nNice to Have:\n• Experience with video editing in Adobe Premiere Pro for social content and product demos\n• Familiarity with Webflow or basic HTML/CSS for implementing design assets directly in web contexts\n• Illustration skills or experience commissioning and directing custom illustration work",
      },
      {
        label: "UX Researcher",
        description:
          "We are looking for a UX Researcher to build a deep, evidence-based understanding of our users and translate those insights into product improvements that create meaningful impact. You will establish research practices, run studies, and make the user's voice heard in every product decision.\n\nResponsibilities:\n• Plan and conduct generative and evaluative research including in-depth interviews, contextual inquiry, diary studies, and usability testing\n• Design surveys using Qualtrics and Typeform and analyze quantitative data to complement qualitative findings\n• Synthesize research findings into clear, compelling deliverables: personas, journey maps, opportunity landscapes, and research reports\n• Partner with product designers, product managers, and engineers to define research questions and integrate findings into decision-making\n• Build and maintain a user research repository using tools such as Dovetail or Notion for cross-team knowledge sharing\n• Recruit research participants through internal panels, Respondent.io, and UserTesting.com\n• Advocate for research-driven product development and coach teams on lightweight research methods\n\nRequirements:\n• 3+ years of UX research experience in a technology product environment\n• Proficiency in a broad range of research methods: semi-structured interviews, usability testing, card sorting, tree testing, surveys, and diary studies\n• Experience with research tools including Maze, UserTesting, Optimal Workshop, Dovetail, and Qualtrics\n• Strong ability to synthesize qualitative and quantitative data into clear, actionable insights\n• Excellent written and verbal communication skills for presenting to executives and cross-functional teams\n• Familiarity with Figma and ability to evaluate prototypes during moderated usability sessions\n• Understanding of statistical concepts for survey analysis, significance testing, and metrics interpretation\n\nNice to Have:\n• Experience with eye-tracking studies, biometric research methods, or lab-based research infrastructure\n• Familiarity with analytics platforms such as Amplitude, Mixpanel, or FullStory for mixed-methods research\n• Background in cognitive psychology, human factors, or social science research methodologies",
      },
    ],
  },
  {
    category: "Product & Management",
    roles: [
      {
        label: "Product Manager",
        description:
          "Our team is seeking a Product Manager to own the strategy, roadmap, and execution for a core product area. You will work at the intersection of user needs, business goals, and technical reality — synthesizing inputs from customers, data, and stakeholders to define what we build and why.\n\nResponsibilities:\n• Own the product roadmap for your area — prioritizing opportunities, writing PRDs, and driving alignment across engineering, design, and business stakeholders\n• Define success metrics for features and track outcomes using Amplitude, Mixpanel, or Google Analytics 4\n• Conduct customer discovery interviews, analyze support feedback, and synthesize insights to inform product direction\n• Partner with UX researchers and designers on research planning, usability studies, and concept validation\n• Manage the full product development lifecycle in Agile sprints using Jira and Confluence\n• Run structured A/B experiments and interpret statistical results to make data-informed feature decisions\n• Communicate product strategy and updates clearly to leadership, customers, and cross-functional teams\n\nRequirements:\n• 4+ years of product management experience at a software or technology company\n• Demonstrated ability to define product strategy, write clear PRDs, and drive cross-functional execution\n• Strong quantitative skills: comfortable with SQL queries, funnel analysis, cohort analysis, and A/B test interpretation\n• Experience with product analytics tools including Amplitude, Mixpanel, or Google Analytics 4\n• Proficiency with Agile methodologies and tools including Jira, Confluence, and sprint-based delivery\n• Excellent written communication skills — ability to write crisp product specs and compelling strategy documents\n• Strong stakeholder management and ability to influence without direct authority\n\nNice to Have:\n• Technical background (CS degree or prior engineering experience) enabling deeper collaboration with engineering teams\n• Experience with product-led growth (PLG) strategies, freemium funnels, and self-serve activation\n• Familiarity with customer feedback platforms such as Productboard, Canny, or Intercom",
      },
      {
        label: "Technical Product Manager",
        description:
          "We are looking for a Technical Product Manager to lead the strategy and execution for our platform, APIs, and developer-facing products. You will bridge the worlds of engineering and product — going deep enough to understand technical tradeoffs while maintaining sharp focus on user and business outcomes.\n\nResponsibilities:\n• Own the roadmap for platform infrastructure, internal APIs, or developer-facing products with a blend of technical depth and product intuition\n• Write detailed technical specifications including API contracts, data models, and system integration requirements\n• Partner directly with engineering leads to evaluate architectural decisions, make build-vs-buy tradeoffs, and establish technical standards\n• Define and track platform KPIs including API latency (p50/p99), error rates, throughput, and developer adoption\n• Prioritize technical debt, reliability improvements, and scalability investments alongside new feature work\n• Manage relationships with third-party API vendors and negotiate integration roadmaps\n• Facilitate sprint planning, backlog grooming, and technical design reviews in Jira and Confluence\n\nRequirements:\n• 4+ years of product management experience with a technical focus on platform, API, or infrastructure products\n• Prior software engineering experience or CS degree strongly preferred\n• Deep understanding of REST API design, JSON, webhooks, OAuth 2.0, and developer experience best practices\n• Experience with cloud platforms (AWS, GCP, or Azure) and ability to read architecture diagrams\n• Familiarity with SQL for data analysis and ability to write queries against PostgreSQL or Snowflake\n• Proficiency with Agile tools including Jira, Confluence, and GitHub for technical project tracking\n• Strong ability to translate engineering complexity into clear product requirements and stakeholder communication\n\nNice to Have:\n• Experience building and launching developer portals, SDKs, or public APIs\n• Familiarity with GraphQL, gRPC, or WebSocket APIs\n• Background in fintech, infrastructure, security, or data platform products",
      },
      {
        label: "Engineering Manager",
        description:
          "Our team is seeking an Engineering Manager to lead a cross-functional engineering team and drive the delivery of high-quality software at pace. You will grow engineers, shape engineering culture, and act as a technical leader who can both zoom in on implementation details and zoom out to organizational strategy.\n\nResponsibilities:\n• Lead, mentor, and grow a team of 6–10 software engineers through regular 1:1s, performance reviews, and career development planning\n• Own delivery of the team's technical roadmap — removing blockers, managing dependencies, and communicating progress to leadership\n• Establish and improve engineering processes including code review standards, sprint ceremonies, incident response, and on-call rotations\n• Collaborate with product managers and designers in roadmap planning, sprint planning, and cross-team coordination\n• Make hiring decisions — conduct technical interviews, evaluate take-home assessments, and build team headcount plans\n• Drive technical architecture discussions and ensure the team's systems are scalable, maintainable, and well-tested\n• Define team OKRs, engineering metrics (DORA metrics, cycle time, defect rate), and hold the team accountable to outcomes\n\nRequirements:\n• 3+ years of engineering management experience leading software development teams of 5+ engineers\n• 6+ years of prior software engineering experience — ability to engage credibly in code reviews and system design discussions\n• Proven track record of delivering complex software projects on schedule with high quality\n• Experience with Agile/Scrum methodologies and tooling including Jira and Confluence\n• Strong engineering judgment and ability to make technology decisions around stack, architecture, and tooling\n• Excellent communication and interpersonal skills for managing up, down, and across the organization\n• Experience with software engineering hiring processes including technical screen design and interview calibration\n\nNice to Have:\n• Experience scaling an engineering organization through rapid headcount growth\n• Familiarity with DORA metrics, engineering effectiveness frameworks, and developer productivity tooling\n• Background as an individual contributor in distributed systems, backend, or platform engineering",
      },
      {
        label: "Scrum Master",
        description:
          "We are looking for a Scrum Master to facilitate Agile ceremonies, coach teams on Scrum practices, and remove impediments that slow down delivery. You will be a servant leader who creates an environment where engineers and product teams can do their best work together.\n\nResponsibilities:\n• Facilitate daily standups, sprint planning, sprint reviews, and retrospectives for one or more Agile engineering teams\n• Coach team members and stakeholders on Scrum values, Agile principles, and self-organizing team practices\n• Identify, track, and actively resolve impediments that block team progress across sprints\n• Maintain and refine the team backlog in Jira with the Product Owner, ensuring stories are well-defined and ready for sprint commitment\n• Track and report on team velocity, burn-down charts, and sprint metrics to identify delivery risks early\n• Facilitate cross-team coordination in a scaled Agile environment (SAFe, LeSS, or Scrum@Scale)\n• Drive continuous improvement through data-informed retrospectives and actionable process changes\n\nRequirements:\n• 3+ years of Scrum Master experience supporting software engineering teams in a tech company\n• Certified ScrumMaster (CSM) or Professional Scrum Master (PSM I/II) certification required\n• Expert proficiency with Jira for backlog management, sprint tracking, and Agile reporting\n• Strong understanding of Scrum, Kanban, and SAFe frameworks and the ability to adapt practices to team context\n• Excellent facilitation skills — able to run effective, engaging ceremonies with diverse teams\n• Strong communication skills and ability to coach both engineers and product stakeholders\n• Comfort with conflict resolution, team dynamics, and navigating organizational dependencies\n\nNice to Have:\n• SAFe Agilist or SAFe Scrum Master (SSM) certification\n• Experience with Confluence for Agile documentation, team wikis, and retrospective records\n• Background working with distributed or remote-first engineering teams across multiple time zones",
      },
      {
        label: "Technical Program Manager",
        description:
          "Our team is seeking a Technical Program Manager to lead the planning, coordination, and execution of large-scale, cross-functional engineering programs. You will ensure complex technical initiatives are delivered on time, within scope, and with clear communication to all stakeholders.\n\nResponsibilities:\n• Lead end-to-end program management for multi-team technical initiatives including platform migrations, API launches, and infrastructure overhauls\n• Define program scope, milestones, risk registers, and communication plans using Jira, Confluence, and Asana\n• Facilitate cross-team dependency mapping, integration planning, and launch readiness reviews\n• Drive technical decision-making forums — documenting outcomes, assigning owners, and tracking follow-through\n• Create executive-level program status reports and communicate trade-offs clearly to senior leadership\n• Manage vendor and third-party partner delivery timelines within the context of larger technical programs\n• Implement program retrospectives and drive process improvements across the engineering organization\n\nRequirements:\n• 5+ years of technical program management experience at a software or technology company\n• Prior software engineering background or CS degree enabling meaningful engagement with technical content\n• Expert proficiency with Jira and Confluence for program tracking, milestone management, and documentation\n• Proven experience managing programs spanning 5+ engineering teams with complex cross-team dependencies\n• Strong understanding of software development lifecycles, release management, and Agile delivery practices\n• Excellent written communication skills — able to produce crisp status updates, risk assessments, and executive summaries\n• PMP or PMI-ACP certification preferred\n\nNice to Have:\n• Experience managing platform migration or cloud infrastructure programs\n• Familiarity with SDLC processes including SOC 2 readiness, penetration testing cycles, and compliance programs\n• Background in scaled Agile frameworks including SAFe or LeSS for large engineering organizations",
      },
      {
        label: "Project Manager",
        description:
          "We are looking for a Project Manager to plan, execute, and close projects across our product and technology organization. You will coordinate resources, manage timelines, mitigate risks, and serve as the connective tissue between teams to ensure initiatives deliver on their goals.\n\nResponsibilities:\n• Develop detailed project plans including scope documents, WBS (work breakdown structures), RACI matrices, and milestone schedules\n• Manage project execution across multiple workstreams using Asana, Jira, and Microsoft Project\n• Run daily and weekly project status meetings, facilitate issue resolution, and maintain stakeholder alignment\n• Identify project risks early, develop mitigation strategies, and escalate blockers to leadership when required\n• Track project budget, resource allocation, and forecast spending against planned estimates\n• Produce regular status reports, executive dashboards, and end-of-project retrospectives\n• Manage relationships with external vendors, agencies, and technology partners throughout the project lifecycle\n\nRequirements:\n• 4+ years of project management experience in a technology, software, or digital services environment\n• PMP (Project Management Professional) certification or equivalent (CAPM, PRINCE2) required\n• Expert proficiency with project management tools including Jira, Asana, Microsoft Project, or Smartsheet\n• Strong understanding of both Agile and Waterfall project methodologies and when to apply each\n• Experience managing project budgets, resource plans, and stakeholder communications at an executive level\n• Proficiency in Microsoft Office Suite and Google Workspace for documentation, reporting, and presentations\n• Excellent organizational, analytical, and written communication skills\n\nNice to Have:\n• Experience managing software development or digital transformation projects\n• Familiarity with Agile/Scrum practices and experience working alongside Scrum Masters and engineering teams\n• Background managing multi-vendor programs with third-party system integrators or offshore development teams",
      },
    ],
  },
  {
    category: "Cybersecurity",
    roles: [
      {
        label: "Security Engineer",
        description:
          "Our team is seeking a Security Engineer to design, build, and maintain the security controls, tooling, and infrastructure that protect our systems, data, and customers. You will work across the full stack — from cloud infrastructure security to application-layer controls — and partner with engineering teams to embed security into the development lifecycle.\n\nResponsibilities:\n• Design and implement security controls across AWS and GCP environments including IAM policies, SCPs, VPC security groups, and WAF configurations\n• Lead threat modeling sessions for new product features and architectural changes using the STRIDE framework\n• Build and maintain SIEM pipelines using Splunk or Elastic SIEM for log aggregation, correlation rules, and alerting\n• Manage vulnerability scanning programs using Qualys or Tenable and drive remediation SLAs with engineering teams\n• Implement secrets management solutions using HashiCorp Vault and enforce certificate lifecycle management\n• Conduct security code reviews and integrate SAST/DAST tooling (Semgrep, Snyk, OWASP ZAP) into CI/CD pipelines\n• Support SOC 2 Type II, ISO 27001, and GDPR compliance programs with technical controls evidence\n\nRequirements:\n• 4+ years of security engineering experience in a cloud-native technology environment\n• Strong knowledge of AWS security services: GuardDuty, Security Hub, CloudTrail, Config, IAM, and KMS\n• Experience with SIEM platforms including Splunk or Elastic SIEM for detection engineering\n• Hands-on experience with vulnerability management tools such as Qualys, Tenable, or Rapid7\n• Familiarity with OWASP Top 10, CWE, and application security testing methodologies\n• Proficiency in Python or Go for security automation, tool development, and infrastructure scripting\n• Understanding of PKI, TLS/mTLS, cryptographic standards, and secrets management\n\nNice to Have:\n• CISSP, CISM, AWS Security Specialty, or GIAC certifications\n• Experience with container security tools including Trivy, Falco, or Aqua Security\n• Background in zero-trust network architecture and identity-aware proxy implementations",
      },
      {
        label: "Security Analyst",
        description:
          "We are looking for a Security Analyst to protect our organization by monitoring security events, investigating threats, supporting compliance programs, and driving security awareness across the business. You will be a critical part of our security operations function, working closely with the Security Engineering team.\n\nResponsibilities:\n• Monitor security alerts from SIEM platforms (Splunk, Microsoft Sentinel) and triage incidents according to severity and response playbooks\n• Investigate potential security incidents including phishing attacks, malware infections, insider threats, and unauthorized access attempts\n• Conduct log analysis across cloud infrastructure (AWS CloudTrail, VPC Flow Logs), endpoint (CrowdStrike), and network security tools\n• Support vulnerability management processes by tracking scan results from Qualys or Tenable and coordinating remediation with engineering teams\n• Perform risk assessments for new vendors, tools, and third-party integrations against SOC 2 and ISO 27001 control frameworks\n• Maintain security policies, incident response runbooks, and security awareness training content\n• Assist with audit evidence collection for SOC 2 Type II, HIPAA, and GDPR compliance assessments\n\nRequirements:\n• 2+ years of security operations, information security, or cybersecurity analyst experience\n• Hands-on experience with SIEM platforms including Splunk, Microsoft Sentinel, or IBM QRadar\n• Familiarity with endpoint detection and response (EDR) tools such as CrowdStrike Falcon, SentinelOne, or Carbon Black\n• Working knowledge of NIST CSF, CIS Controls, SOC 2, and ISO 27001 frameworks\n• Strong understanding of networking fundamentals: TCP/IP, DNS, HTTP/S, firewall rules, and VPNs\n• CompTIA Security+, CompTIA CySA+, or equivalent certification required\n• Proficiency with ticketing systems including Jira or ServiceNow for incident tracking\n\nNice to Have:\n• Experience with threat intelligence platforms such as MISP or Recorded Future\n• Familiarity with MITRE ATT&CK framework for threat hunting and detection rule development\n• CEH (Certified Ethical Hacker) or GIAC GSEC certification",
      },
      {
        label: "Penetration Tester",
        description:
          "Our team is seeking a Penetration Tester to assess the security posture of our applications, infrastructure, and cloud environments through rigorous, real-world offensive security testing. You will help us find and remediate vulnerabilities before adversaries do, and raise the security bar across the engineering organization.\n\nResponsibilities:\n• Conduct web application penetration tests targeting OWASP Top 10 vulnerabilities including SQLi, XSS, IDOR, SSRF, and authentication flaws\n• Perform network and infrastructure penetration testing against internal and external perimeters using Nmap, Metasploit, and Burp Suite Pro\n• Execute cloud security assessments against AWS and Azure environments evaluating IAM misconfigurations, exposed S3 buckets, and privilege escalation paths\n• Develop and run custom exploit scripts and proof-of-concept code in Python to demonstrate vulnerability impact\n• Produce clear, detailed penetration test reports for both technical and executive audiences including risk ratings, reproduction steps, and remediation guidance\n• Perform red team engagements simulating realistic adversary TTPs using the MITRE ATT&CK framework\n• Support bug bounty program triage and collaborate with security engineers on remediation validation\n\nRequirements:\n• 3+ years of penetration testing or offensive security experience across web applications and network infrastructure\n• Proficiency with Burp Suite Pro, Metasploit Framework, Nmap, Nessus, and BloodHound\n• Strong web application security knowledge covering OWASP Top 10 and API security vulnerabilities\n• Hands-on cloud security testing experience in AWS or Azure environments\n• Proficiency in Python for exploit scripting, automation, and payload development\n• OSCP (Offensive Security Certified Professional) certification required\n• Experience writing professional penetration test reports with CVSS-scored findings and remediation recommendations\n\nNice to Have:\n• OSEP, OSWE, or OSED certifications for specialized offensive security expertise\n• Experience with Active Directory attacks including Kerberoasting, Pass-the-Hash, and DCSync\n• Background in social engineering assessment methodologies including phishing simulations",
      },
      {
        label: "SOC Analyst",
        description:
          "We are looking for a SOC Analyst to join our Security Operations Center and serve as a critical line of defense against cyber threats. You will monitor, detect, investigate, and respond to security incidents in real time, protecting our infrastructure, data, and customers 24/7.\n\nResponsibilities:\n• Monitor security alerts in real time across SIEM platforms (Splunk, Microsoft Sentinel) and analyze events for indicators of compromise (IOCs)\n• Triage and investigate security incidents including phishing, malware, ransomware, and unauthorized access events according to defined incident response playbooks\n• Perform threat hunting using MITRE ATT&CK TTPs to proactively identify adversary presence in our environment\n• Analyze network traffic, endpoint telemetry (CrowdStrike, SentinelOne), and cloud audit logs (AWS CloudTrail, Azure Monitor)\n• Escalate confirmed incidents to Tier 2/3 analysts and Security Engineers with documented initial analysis and containment actions\n• Write and tune SIEM detection rules and correlation logic to reduce false positives and improve detection fidelity\n• Document investigation findings in ServiceNow or Jira and contribute to post-incident reviews and lessons-learned sessions\n\nRequirements:\n• 2+ years of SOC analyst experience or a Tier 1/2 security operations role\n• Hands-on experience with Splunk, Microsoft Sentinel, or IBM QRadar for alert monitoring and investigation\n• Working knowledge of endpoint detection and response tools including CrowdStrike Falcon or SentinelOne\n• Understanding of networking protocols: TCP/IP, HTTP/S, DNS, SMTP, and VPN\n• Familiarity with MITRE ATT&CK framework for threat categorization and investigation guidance\n• CompTIA Security+ or CompTIA CySA+ certification required\n• Strong analytical skills and ability to work calmly under pressure during active incident response\n\nNice to Have:\n• Experience with SOAR platforms such as Splunk SOAR (Phantom) or Palo Alto XSOAR for automated response playbooks\n• Familiarity with malware analysis fundamentals and sandboxing using Any.run or Cuckoo\n• Willingness to work rotating shifts including weekends and holidays to support 24/7 SOC coverage",
      },
    ],
  },
  {
    category: "Business & Marketing",
    roles: [
      {
        label: "Business Analyst",
        description:
          "Our team is seeking a Business Analyst to bridge the gap between business stakeholders and technology teams, translating complex operational challenges into clear, actionable requirements that drive product and process improvements.\n\nResponsibilities:\n• Elicit, document, and validate business requirements through stakeholder interviews, workshops, and process walkthroughs\n• Develop detailed Business Requirements Documents (BRDs), functional specifications, user stories, and acceptance criteria in Confluence and Jira\n• Model and analyze business processes using BPMN notation and tools such as Lucidchart or Visio\n• Analyze operational data using SQL and Excel (pivot tables, VLOOKUP, Power Query) to identify process inefficiencies and opportunities\n• Facilitate requirements reviews, UAT planning sessions, and sign-off meetings with business and technology stakeholders\n• Create Tableau or Power BI dashboards to track KPIs and provide ongoing business performance visibility\n• Support change management activities including training material development and user adoption tracking\n\nRequirements:\n• 3+ years of business analysis experience in a technology or software-driven organization\n• Strong SQL skills for data extraction and analysis against relational databases (PostgreSQL, SQL Server)\n• Proficiency in Jira and Confluence for requirements documentation and Agile backlog management\n• Solid experience with process modeling tools such as Lucidchart, Visio, or draw.io\n• Hands-on experience creating reports and dashboards in Tableau or Power BI\n• Excellent written communication skills — ability to write clear BRDs, user stories, and process documentation\n• CBAP (Certified Business Analysis Professional) or ECBA certification preferred\n\nNice to Have:\n• Experience with ERP systems such as SAP, Oracle, or Salesforce in an analyst capacity\n• Familiarity with Agile and SAFe methodologies including writing epics, features, and user stories\n• Background in financial services, healthcare, or ecommerce verticals",
      },
      {
        label: "Digital Marketing Manager",
        description:
          "We are looking for a Digital Marketing Manager to lead our paid and organic digital marketing programs, drive measurable growth, and optimize the full customer acquisition funnel across search, social, display, and email channels.\n\nResponsibilities:\n• Plan, execute, and optimize paid media campaigns across Google Ads, Meta Ads Manager, and LinkedIn Campaign Manager with monthly budgets exceeding $250K\n• Own SEO strategy and execution including on-page optimization, technical SEO audits, and link building using Ahrefs and Semrush\n• Develop and execute email marketing campaigns using HubSpot or Marketo including segmentation, automation flows, and A/B testing\n• Manage conversion rate optimization (CRO) initiatives using Google Optimize, VWO, or Optimizely\n• Analyze campaign performance using Google Analytics 4, Looker, and Tableau to surface insights and inform budget allocation\n• Collaborate with content and design teams to develop landing pages, ad creatives, and campaign assets\n• Track and report on CAC, ROAS, LTV, and pipeline contribution metrics to senior marketing leadership\n\nRequirements:\n• 4+ years of digital marketing experience with hands-on ownership of paid media budgets\n• Expert proficiency with Google Ads, Meta Ads Manager, and LinkedIn Campaign Manager\n• Strong SEO expertise using tools such as Ahrefs, Semrush, and Google Search Console\n• Experience with marketing automation platforms including HubSpot, Marketo, or Pardot\n• Solid analytical skills with proficiency in Google Analytics 4, Looker, and Excel\n• Google Ads Certification and Meta Blueprint Certification preferred\n• Understanding of attribution modeling, UTM tracking, and multi-touch funnel analysis\n\nNice to Have:\n• Experience with programmatic advertising using The Trade Desk or DV360\n• Familiarity with CDP platforms such as Segment, Rudderstack, or Klaviyo for audience management\n• Background in B2B SaaS demand generation and ABM (Account-Based Marketing) strategies",
      },
      {
        label: "SEO Specialist",
        description:
          "Our team is seeking an SEO Specialist to drive organic search growth by executing a comprehensive strategy covering technical SEO, content optimization, and link acquisition. You will have measurable impact on our website traffic, search rankings, and organic pipeline.\n\nResponsibilities:\n• Conduct comprehensive technical SEO audits using Screaming Frog, Ahrefs, and Google Search Console — identifying and resolving crawlability, indexation, Core Web Vitals, and structured data issues\n• Perform keyword research and competitive gap analysis using Ahrefs and Semrush to inform content strategy and page optimization\n• Optimize on-page SEO elements including meta titles, meta descriptions, header hierarchy, internal linking, and schema markup (JSON-LD)\n• Lead content optimization initiatives by updating existing pages and briefing new content to hit topical authority targets\n• Build and manage white-hat link acquisition campaigns including digital PR, content partnerships, and broken link building\n• Monitor and report on organic traffic, keyword rankings, impressions, and CTR using Google Analytics 4 and Looker Studio\n• Collaborate with web development teams to implement technical SEO recommendations via HTML, JavaScript, and CMS configurations\n\nRequirements:\n• 3+ years of SEO experience in-house or at a digital marketing agency\n• Expert proficiency with Ahrefs, Semrush, Moz Pro, and Google Search Console\n• Strong technical SEO knowledge including crawl budget optimization, Core Web Vitals, hreflang, canonical tags, and XML sitemaps\n• Proficiency in Google Analytics 4 and Looker Studio for organic performance reporting\n• Working knowledge of HTML, CSS, and JavaScript sufficient to identify and communicate SEO implementation issues\n• Experience with structured data markup (Schema.org, JSON-LD) and rich snippet optimization\n• Understanding of Google's algorithm updates and E-E-A-T quality guidelines\n\nNice to Have:\n• Experience with programmatic SEO and large-scale page generation for ecommerce or marketplace sites\n• Familiarity with log file analysis using tools such as Botify or Splunk for crawl behavior investigation\n• Background in international SEO, hreflang implementation, and multilingual content strategies",
      },
      {
        label: "Content Writer",
        description:
          "We are looking for a Content Writer to produce high-quality, SEO-optimized content across our blog, documentation, case studies, email campaigns, and social channels. You will be a skilled storyteller who can translate complex technical concepts into compelling narratives for diverse audiences.\n\nResponsibilities:\n• Research, write, and edit long-form blog articles (1,500–3,000 words) optimized for target keywords using Ahrefs and Semrush keyword data\n• Develop case studies, white papers, ebooks, and landing page copy that support demand generation and sales enablement\n• Write and A/B test email sequences for nurture campaigns in HubSpot including subject lines, body copy, and CTAs\n• Collaborate with the SEO team to align content with keyword strategy, internal linking architecture, and search intent\n• Maintain and update the brand voice and style guide ensuring consistency across all written content\n• Produce technical documentation, product explainers, and integration guides in Notion or Confluence for developer and end-user audiences\n• Manage content calendars and deliver consistently against editorial deadlines\n\nRequirements:\n• 3+ years of content writing experience for a B2B technology, SaaS, or digital media brand\n• Exceptional written English with demonstrated ability to adapt tone and style for different audiences\n• Strong working knowledge of SEO content principles including keyword targeting, search intent alignment, and on-page optimization\n• Experience with content management systems including WordPress, Webflow, or Contentful\n• Familiarity with HubSpot or Marketo for email campaign content development\n• Ability to use Ahrefs, Semrush, or Google Search Console to inform content strategy and track performance\n• Strong research skills and comfort interviewing subject matter experts for technical content\n\nNice to Have:\n• Experience writing for developer audiences: API documentation, SDK guides, or engineering blog posts\n• Familiarity with Grammarly Business, Hemingway Editor, and AI writing tools used responsibly\n• Background in journalism, technical writing, or digital publishing",
      },
      {
        label: "Growth Marketing Manager",
        description:
          "Our team is seeking a Growth Marketing Manager to own our full-funnel acquisition, activation, and retention experiments. You will drive measurable growth through data-driven experimentation across paid, organic, product, and lifecycle marketing channels.\n\nResponsibilities:\n• Design and run rapid growth experiments across acquisition channels including Google Ads, Meta, LinkedIn, and SEO, applying a rigorous test-measure-learn framework\n• Own the conversion rate optimization (CRO) roadmap for marketing site and app onboarding flows using Optimizely and Hotjar\n• Build and optimize lifecycle marketing automation in HubSpot or Iterable including onboarding sequences, re-engagement campaigns, and behavioral triggers\n• Analyze funnel performance using Amplitude or Mixpanel, identifying drop-off points and running targeted experiments to improve activation rates\n• Manage referral programs, affiliate channels, and partnership initiatives to drive low-CAC acquisition\n• Track and report on North Star metrics including CAC, LTV, ROAS, activation rate, and 30/60/90-day retention to executive leadership\n• Collaborate with product, engineering, and design teams to implement growth-focused product experiments\n\nRequirements:\n• 4+ years of growth marketing experience in a B2C or B2B SaaS environment\n• Demonstrated experience designing and analyzing A/B tests and multi-variate experiments with statistical rigor\n• Proficiency with product analytics tools including Amplitude, Mixpanel, or Heap\n• Hands-on experience with paid acquisition channels (Google Ads, Meta) and lifecycle marketing tools (HubSpot, Iterable, or Braze)\n• Strong SQL skills for cohort analysis, funnel queries, and retention analysis\n• Familiarity with attribution modeling, UTM parameter governance, and multi-touch funnel reporting\n• Comfort with Google Analytics 4 and Looker for campaign performance reporting\n\nNice to Have:\n• Experience with product-led growth (PLG) strategies including self-serve onboarding optimization\n• Familiarity with CDP platforms such as Segment for audience building and event tracking\n• Background in viral growth mechanics, referral loop design, or community-led growth strategies",
      },
    ],
  },
  {
    category: "Other Technical",
    roles: [
      {
        label: "Database Administrator",
        description:
          "We are looking for a Database Administrator to manage, optimize, and secure our production database infrastructure supporting millions of daily transactions. You will ensure high availability, peak performance, and data integrity across our PostgreSQL, MySQL, and MongoDB environments.\n\nResponsibilities:\n• Administer, monitor, and optimize PostgreSQL and MySQL database instances on AWS RDS and Aurora including parameter tuning, index optimization, and query plan analysis\n• Design and implement backup, point-in-time recovery, and disaster recovery strategies with defined RPO and RTO targets\n• Perform capacity planning, storage management, and database scaling including read replica configuration and sharding strategies\n• Monitor database health using Datadog, pgBadger, and AWS CloudWatch — proactively resolving performance bottlenecks\n• Implement database security controls including role-based access control (RBAC), encryption at rest (AES-256), encryption in transit (TLS), and audit logging\n• Manage schema migrations using Flyway or Liquibase in coordination with development teams\n• Evaluate and implement new database technologies including Redis, MongoDB, and DynamoDB for appropriate use cases\n\nRequirements:\n• 4+ years of database administration experience in a production environment\n• Expert proficiency with PostgreSQL including VACUUM, ANALYZE, EXPLAIN ANALYZE, index types (B-tree, GIN, GiST), and replication\n• Strong working knowledge of MySQL and Aurora MySQL in AWS RDS environments\n• Hands-on experience with AWS RDS, Aurora, DynamoDB, and ElastiCache for Redis\n• Proficiency in writing complex SQL and stored procedures for data management and reporting\n• Experience with Flyway or Liquibase for version-controlled schema migration management\n• Solid understanding of database security, encryption, access control, and compliance requirements\n\nNice to Have:\n• Experience with MongoDB Atlas administration including replica sets, sharding, and aggregation pipeline optimization\n• Familiarity with database performance benchmarking using pgBench or sysbench\n• AWS Certified Database Specialty certification",
      },
      {
        label: "Network Engineer",
        description:
          "Our team is seeking a Network Engineer to design, implement, and maintain the enterprise and cloud network infrastructure that connects our global operations. You will ensure network reliability, security, and performance at scale while supporting rapid infrastructure growth.\n\nResponsibilities:\n• Design, configure, and maintain LAN/WAN network infrastructure using Cisco and Juniper routing and switching equipment\n• Implement and manage SD-WAN solutions using Cisco Meraki or VMware VeloCloud across multiple office and data center locations\n• Configure and manage BGP, OSPF, and EIGRP routing protocols for internal and external peering\n• Design and maintain network security architecture including next-generation firewalls (Palo Alto Networks, Fortinet), IDS/IPS, and network segmentation using VLANs and ACLs\n• Manage AWS Direct Connect and VPN tunnels for hybrid cloud connectivity\n• Monitor network performance using SolarWinds, PRTG, and Datadog NPM — resolving performance and availability issues\n• Develop and maintain network architecture diagrams and operational runbooks\n\nRequirements:\n• 4+ years of network engineering experience in an enterprise or cloud-hybrid environment\n• Expert knowledge of networking protocols: TCP/IP, BGP, OSPF, EIGRP, STP, VXLAN, and VPN\n• Hands-on experience with Cisco IOS/NX-OS and Juniper Junos configuration and troubleshooting\n• Experience with Palo Alto Networks or Fortinet next-generation firewalls and Panorama management\n• Working knowledge of AWS networking services including VPC, Direct Connect, Transit Gateway, and Route 53\n• Proficiency with network monitoring and management tools including SolarWinds, PRTG, or Wireshark\n• CCNA or CCNP certification required; CCIE preferred\n\nNice to Have:\n• Experience with network automation using Python, Ansible, and NAPALM for configuration management\n• Familiarity with SD-WAN platforms including Cisco Meraki, VMware VeloCloud, or Palo Alto Prisma SD-WAN\n• Knowledge of IPv6 deployment and dual-stack network architecture",
      },
      {
        label: "Systems Administrator",
        description:
          "We are looking for a Systems Administrator to maintain and optimize the IT infrastructure that keeps our engineering and business teams productive. You will manage servers, identity systems, endpoints, and cloud infrastructure while ensuring security and operational excellence.\n\nResponsibilities:\n• Administer Linux (Ubuntu, RHEL, CentOS) and Windows Server environments including user management, patching, and performance monitoring\n• Manage cloud infrastructure on AWS including EC2 instances, IAM roles, S3 buckets, and VPC configurations\n• Administer identity and access management platforms including Okta, Active Directory, and Google Workspace\n• Manage endpoint configuration and security using Jamf Pro (macOS) and Microsoft Intune for Windows and mobile device management\n• Implement and maintain patch management processes using AWS Systems Manager, WSUS, and Ansible\n• Monitor system health using Datadog, Nagios, and CloudWatch — responding to alerts and resolving incidents\n• Develop automation scripts in Bash and Python to reduce manual operational tasks and enforce configuration consistency\n\nRequirements:\n• 3+ years of systems administration experience in a technology organization\n• Strong Linux administration skills (Ubuntu, RHEL) including shell scripting, cron jobs, systemd, and log management\n• Hands-on experience with AWS including EC2, S3, VPC, IAM, and Systems Manager\n• Proficiency with identity platforms including Okta and Active Directory for user provisioning and SSO\n• Experience with endpoint management using Jamf Pro and/or Microsoft Intune\n• Scripting proficiency in Bash and Python for automation and configuration management\n• CompTIA Linux+, Red Hat Certified System Administrator (RHCSA), or AWS SysOps Administrator certification preferred\n\nNice to Have:\n• Experience with configuration management tools such as Ansible, Chef, or Puppet\n• Familiarity with containerization using Docker and basic Kubernetes administration\n• Background supporting SOC 2 compliance evidence collection and IT security audits",
      },
      {
        label: "Technical Writer",
        description:
          "Our team is seeking a Technical Writer to produce clear, accurate, and developer-friendly documentation for our APIs, SDKs, platform integrations, and internal engineering processes. You will make complex technical concepts accessible and enable developers and users to get value from our product faster.\n\nResponsibilities:\n• Write, maintain, and continuously improve API reference documentation, developer guides, quickstarts, and integration tutorials\n• Collaborate with software engineers, product managers, and developer relations to gather technical content and validate accuracy\n• Develop and maintain developer-facing documentation sites using tools such as Docusaurus, GitBook, or Readme.io\n• Create structured OpenAPI (Swagger) documentation for REST APIs and maintain API changelog records\n• Produce clear internal documentation including architecture decision records (ADRs), runbooks, and incident post-mortem templates in Confluence\n• Conduct documentation audits, identify content gaps, and prioritize improvements based on developer feedback and support ticket analysis\n• Establish documentation style guides and contribute to the company's documentation-as-code workflows using Git and Markdown\n\nRequirements:\n• 3+ years of technical writing experience focused on software developer documentation or API documentation\n• Strong portfolio of published developer documentation including API references, tutorials, and SDK guides\n• Proficiency with Markdown, reStructuredText, and documentation site generators (Docusaurus, MkDocs, or GitBook)\n• Experience with OpenAPI (Swagger) specification for REST API documentation\n• Comfort working in a Git-based documentation workflow including branching, pull requests, and version control\n• Strong ability to read code samples in Python, JavaScript, or similar languages and write accurate corresponding documentation\n• Excellent written communication skills with meticulous attention to accuracy and clarity\n\nNice to Have:\n• Experience with DITA (Darwin Information Typing Architecture) or structured authoring tools for large documentation sets\n• Familiarity with developer experience tools including Postman for API testing and documentation validation\n• Background using Readme.io, Stoplight, or Redocly for API documentation publishing",
      },
      {
        label: "Solutions Architect",
        description:
          "We are looking for a Solutions Architect to work closely with enterprise customers, translating complex business requirements into scalable, secure, and cost-effective technical architectures using our platform and cloud infrastructure. You will be a trusted technical advisor throughout the pre-sales and post-sales lifecycle.\n\nResponsibilities:\n• Lead technical discovery sessions with enterprise customers to understand requirements, constraints, and integration challenges\n• Design end-to-end solution architectures using AWS services (EC2, RDS, S3, Lambda, API Gateway, CloudFront) and our platform APIs\n• Create architecture diagrams, solution briefs, and technical proposals using draw.io, Lucidchart, and AWS Architecture Center templates\n• Deliver technical presentations, product demonstrations, and proof-of-concept builds to CTO and VP-level enterprise audiences\n• Guide customers through technical onboarding, integration design, and production readiness reviews\n• Partner with product and engineering teams to surface customer requirements and influence roadmap priorities\n• Develop reusable reference architectures, integration patterns, and best practice documentation for the solutions library\n\nRequirements:\n• 5+ years of solutions architecture, pre-sales engineering, or senior cloud engineering experience\n• AWS Certified Solutions Architect Professional or equivalent GCP/Azure certification required\n• Deep expertise with AWS services including VPC, EC2, RDS, Lambda, API Gateway, S3, CloudFront, and IAM\n• Strong knowledge of REST API design, microservices architecture, and enterprise integration patterns\n• Experience designing for enterprise requirements including SSO (SAML, OIDC), SOC 2 compliance, and data residency\n• Excellent technical communication skills — ability to tailor content from hands-on engineering teams to C-suite executives\n• Proficiency with Terraform for infrastructure-as-code in customer-facing architecture demonstrations\n\nNice to Have:\n• Experience with multi-cloud architectures spanning AWS, GCP, and Azure\n• Background in financial services, healthcare (HIPAA), or regulated industry architecture requirements\n• Familiarity with Kubernetes, service mesh, and cloud-native patterns for large-scale enterprise deployments",
      },
      {
        label: "Blockchain Developer",
        description:
          "Our team is seeking a Blockchain Developer to design and build secure, efficient smart contracts and decentralized applications on Ethereum and EVM-compatible chains. You will work at the forefront of Web3 technology, contributing to protocols, tooling, and user-facing dApps.\n\nResponsibilities:\n• Design, develop, test, and audit smart contracts in Solidity for Ethereum, Polygon, and Arbitrum using Hardhat and Foundry\n• Build decentralized application (dApp) frontends using React, TypeScript, ethers.js, and Wagmi\n• Implement and integrate DeFi protocols including ERC-20, ERC-721, ERC-1155, and ERC-4626 vault standards\n• Write comprehensive smart contract test suites using Foundry (Forge) and Hardhat with coverage targets above 95%\n• Conduct internal security reviews and threat modeling for smart contracts — addressing reentrancy, overflow, front-running, and access control vulnerabilities\n• Integrate with IPFS, Filecoin, and decentralized storage solutions for on-chain metadata and asset storage\n• Monitor on-chain protocol performance and user activity using Dune Analytics and The Graph subgraphs\n\nRequirements:\n• 3+ years of smart contract development experience in Solidity on Ethereum or EVM-compatible chains\n• Expert proficiency in Solidity and deep understanding of EVM execution model, gas optimization, and storage layout\n• Hands-on experience with Hardhat and Foundry for smart contract development, testing, and deployment\n• Strong proficiency in TypeScript and experience with ethers.js, Wagmi, and Viem for Web3 frontend integration\n• Solid understanding of DeFi protocol mechanics: AMMs, lending protocols, yield aggregators, and stablecoin designs\n• Familiarity with OpenZeppelin contract libraries and proxy upgrade patterns (UUPS, Transparent Proxy)\n• Knowledge of common smart contract vulnerabilities and EVM security best practices\n\nNice to Have:\n• Experience with formal verification tools such as Certora Prover or Echidna for fuzz testing\n• Familiarity with Layer 2 scaling solutions including Arbitrum, Optimism, and zkSync architecture\n• Prior collaboration with professional smart contract auditing firms (Trail of Bits, OpenZeppelin, Consensys Diligence)",
      },
    ],
  },
];

export function getJobDescription(label: string): string | null {
  for (const cat of JOB_CATEGORIES) {
    const role = cat.roles.find((r) => r.label === label);
    if (role) return role.description;
  }
  return null;
}